version: '3.8'
services:
  app:
    build: .
    container_name: financial-product-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/<database_name>
      SPRING_DATASOURCE_USERNAME: <your_username>
      SPRING_DATASOURCE_PASSWORD: <your_password>

  postgres:
    image: postgres:15
    container_name: financial-product-db
    restart: on-failure
    environment:
      POSTGRES_DB: <database_name>
      POSTGRES_USER: <your_username>
      POSTGRES_PASSWORD: <your_password>
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
