# Spring configs
spring:
  application:
    name: financial-product

  # Jpa
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  # DataSource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/finance
    username: postgres
    password: postgres

  # PORT
server:
  port: 8080

  # Token expired date
tokens:
  access:
    expiration-time: 6000
  refresh:
    expiration-time: 60000
  sign-key: 6250655367566B5970337336763979244226452948404D635166546A576D5A71
